version: 0.1
phases:
  build:
    commands:
      - echo "**** Starting build"
      - echo "**** Running tests"
      #- cd tests ; pytest -v -s
      - cd tests ; pytest -v -s unit/helpers/test_Lambda_Package.py