version: 0.1
phases:
  install:
    commands:
      - pip3 uninstall -y osbot-aws       # remove since we want to use the version for the source code (not from the docker instance)
  build:
    commands:
      - echo "**** Starting build"
      - echo "**** Running tests"
      - cd tests ; pytest -v -s -W ignore::DeprecationWarning
      #- cd tests ; pytest -v -s unit/helpers/test_Lambda_Package.py